
% Essa função implementa a Seleção por Torneio, calculando a nota dos
% indivíduos e selecionando os NPP melhores

function [paiss] = funcaonotas(populacaoo,tamanhoentrada,MM,tamanhosaida)
populacaoAux = populacaoo;
auxP = populacaoo;
notaspopulacao = zeros(tamanhoentrada,1);

for i=1:tamanhoentrada

    % obtendo da matriz MM os custos de uma cidade para outra e somando
    notaspopulacao(i,:) = MM((auxP(i,1)),(auxP(i,2))) ...
                        + MM((auxP(i,2)),(auxP(i,3))) ...
                        + MM((auxP(i,3)),(auxP(i,4))) ...
                        + MM((auxP(i,4)),(auxP(i,5))) ...
                        + MM((auxP(i,5)),(auxP(i,6))) ...
                        + MM((auxP(i,6)),(auxP(i,7))) ...
                        + MM((auxP(i,7)),(auxP(i,8))) ...
                        + MM((auxP(i,8)),(auxP(i,9))) ...
                        + MM((auxP(i,9)),(auxP(i,10))) ...
                        + MM((auxP(i,10)),(auxP(i,11))) ...
                        + MM((auxP(i,11)),(auxP(i,12))) ...
                        + MM((auxP(i,12)),(auxP(i,13))) ...
                        + MM((auxP(i,13)),(auxP(i,14))) ...
                        + MM((auxP(i,14)),(auxP(i,1)));
end

for i=1:tamanhoentrada
    % calculando a nota da população e adicionando no final de cada indivíduo a sua respectiva nota
    % quanto menor o custo de caminho, maior a nota
    notaspopulacao(i,:) = (1 / (notaspopulacao(i,:))) * 1000;
    populacaoAux(i,15) = notaspopulacao(i,:);
end

populacaoAux2 = flipud(sortrows(populacaoAux,15)); %ordena da maior nota para a menor
paiss = zeros(tamanhosaida,15);

for k=1:tamanhosaida
    % selecionando tamanhosaida pais para gerar filhos posteriormente
    paiss(k,:) = populacaoAux2(k,:);
end